Softvision.Web/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Softvision.BL.Crud;
using Softvision.BL.Entities;

namespace Softvision.All.Controllers
{
    public class AuthorController : Controller
    {
        // GET: Author
        public ActionResult Index()
        {
            List<UserBL> authors = KitBL.Instance.Users.GetAll();
            authors = authors.Where(u => u.isDeleted == 0).ToList();

            return View(authors);
        }

        // GET: Author/Details/5
        public ActionResult Details(int id)
        {
            var author = KitBL.Instance.Users.GetById(id);

            if (author == null)
            {
                return RedirectToAction("Index");
            }
            return View(author);
        }

        // GET: Author/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Author/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Author/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Author/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Author/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Author/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Softvision.Web/Views/Author/Details.cshtml
@model Softvision.BL.Entities.UserBL

@{
    ViewBag.Title = @Model.FirstName+ @Model.LastName+"- Author";
}

<h2>@Model.FirstName @Model.LastName</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
           Member Since
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JoinDate)
        </dd>

        <dt>
            Contact info:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>
</div>

Softvision.Web/Views/Author/Index.cshtml
@model IEnumerable<Softvision.BL.Entities.UserBL>

@{
    ViewBag.Title = "Authors & Colaborators";
}

<h2>Authors and colaborators</h2>

<p>
    @Html.ActionLink("Become an author!", "Register", "User")
</p>
@foreach (var item in Model)
{
    <div class="userSquareMain">
        <div class="userSquareAuthor">

        </div>
        <div>
            @Html.ActionLink(@item.FirstName, "Details", "Author", new { id = item.Id }, null)
        </div>
    </div>
}